version: '3.7'
services:
    nginx:
        image: nginx:alpine
        ports:
            - "5000:5000"
            - "5001:5001"
            - "8000:8000"
        volumes:
            - ./docker/development/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/development/nginx/auth/htpasswd:/etc/nginx/auth/htpasswd
        depends_on:
            - registry
            - cache-registry
            - jenkins

    registry:
        image: registry:2
        volumes:
            - registry:/var/lib/registry

    cache-registry:
        image: registry:2
        restart: always
        environment:
            REGISTRY_PROXY_REMOTEURL: https://registry-1.docker.io
            REGISTRY_STORAGE_DELETE_ENABLED: 1
        volumes:
            - cache-registry:/var/lib/registry

    jenkins:
        build:
            context: ./docker/common/jenkins
        environment:
            DOCKER_HOST: tcp://docker:2376
            DOCKER_CERT_PATH: /certs/client
            DOCKER_TLS_VERIFY: 1
        volumes:
            - jenkins-data:/var/jenkins_home
            - docker-certs:/certs/client:ro
        depends_on:
            - docker

    docker:
        build:
            context: ./docker/production/dind
        privileged: true
        environment:
            DOCKER_TLS_CERTDIR: /certs
        volumes:
            - /etc/docker/dind-daemon.json:/etc/docker/daemon.json:ro
            - jenkins-data:/var/jenkins_home
            - docker-certs:/certs/client
            - docker-data:/var/lib/docker

volumes:
    registry:
    cache-registry:
    jenkins-data:
    docker-certs:
    docker-data: